name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    
    steps:
      # 1. Клонируем репозиторий
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # 4. Генерируем JSON из CSV
      - name: Build data
        run: npm run build:data

      # 5. Собираем React-приложение
      - name: Build React app
        run: npm run build

      # 6. Деплоим папку build на сервер
      - name: Deploy files via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: processormuseum.narod.ru
          username: oprocessormuseum
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./build/
          server-dir: ./
          protocol: ftp
          port: 21
          log-level: verbose
