name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    
    steps:
      # 1. Клонируем репозиторий
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # 4. Генерируем JSON из CSV
      - name: Build data
        run: npm run build:data

      # 5. Собираем React-приложение
      - name: Build React app
        run: npm run build

      # Шаг 1: Удаляем старые js/css файлы
      - name: Clean old js/css files
        uses: haukurh/lftp-action@v1
        with:
          ftp_host: ${{ vars.FTP_HOST }}
          ftp_user: ${{ vars.FTP_USER }}
          ftp_pass: ${{ secrets.FTP_PASS }}
          ftp_protocol: ftp
          ftp_port: 21
          force_ssl: false
          commands: |
            set ftp:passive-mode true
            cd static/js
            rm -f main.*.js
            rm -f main.*.js.map
            rm -f *.LICENSE.txt
            cd ../css
            rm -f main.*.css
            cd ../..

      # Шаг 2: Загружаем новую сборку
      - name: Deploy new build
        uses: haukurh/lftp-action@v1
        with:
          ftp_host: ${{ vars.FTP_HOST }}
          ftp_user: ${{ vars.FTP_USER }}
          ftp_pass: ${{ secrets.FTP_PASS }}
          ftp_protocol: ftp
          ftp_port: 21
          force_ssl: false
          commands: |
            set ftp:passive-mode true
            mirror --continue --reverse --verbose build/ ./
